# Generated by Django 4.1.4 on 2022-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='blank_profile', upload_to='profile_images'),
        ),
    ]
