# Generated by Django 4.1.4 on 2022-12-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
