# Generated by Django 4.1.4 on 2022-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True),
        ),
    ]
