# Generated by Django 4.1.4 on 2022-12-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_roommate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_roommates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality_types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleeping_habits',
            field=models.TextField(blank=True),
        ),
    ]
