# Generated by Django 4.1.4 on 2023-06-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Roommate_Post',
        ),
    ]
